apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
        version: v1
    spec:
      containers:
      - name: product-service
        image: jamesmedice/product-service
        imagePullPolicy: Never
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  ports:
  - port: 9999
    targetPort: 30500
    name: http
  selector:
    app: product-service
---