apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-virtual-service
spec:
  hosts:
  - "apiserver.istioinaction.io"
  gateways:
  - product-gateway
  http:
  - route:
    - destination:
        host: product-service
        port:
          number: 9999